import { chromium } from 'playwright'
const B='http://127.0.0.1:8787'
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' })
const ctx = await browser.newContext({ viewport: { width: 1400, height: 1000 } })
const page = await ctx.newPage()
page.on('pageerror', e=>console.log('PAGEERROR', e.message))
page.on('console', m=>m.type()==='error'&&console.log('CONSOLE', m.text()))
const pages = await (await fetch(`${B}/api/dashboards`)).json()
const id = s => pages.dashboards.find(d=>d.slug===s).id
await page.goto(`${B}/d/${id('health')}`, {waitUntil:'networkidle'})
await page.waitForTimeout(2500)
const heads = await page.$$eval('.drift-group h4, h4', els=>els.map(e=>e.textContent))
console.log('drift group headings:', heads)
const whys = await page.$$eval('.drift-why', els=>els.map(e=>e.textContent.slice(0,60)))
console.log('why lines:', whys.length, whys)
await page.screenshot({ path: '/tmp/claude-0/-home-user-architecture-map/7d35314f-8f0f-5823-8403-2b1bfb14eb8a/scratchpad/health.png', fullPage: true })
await page.goto(`${B}/d/${id('processes')}`, {waitUntil:'networkidle'})
await page.waitForTimeout(3000)
await page.screenshot({ path: '/tmp/claude-0/-home-user-architecture-map/7d35314f-8f0f-5823-8403-2b1bfb14eb8a/scratchpad/procpage.png', fullPage: true })
console.log('proc page ok')
await page.goto(`${B}/process?code=3.1.1`, {waitUntil:'networkidle'})
await page.waitForTimeout(600)
const findings = await page.$$eval('.card li', els=>els.map(e=>e.textContent.slice(0,120)))
console.log('3.1.1 page list items:', findings)
await page.screenshot({ path: '/tmp/claude-0/-home-user-architecture-map/7d35314f-8f0f-5823-8403-2b1bfb14eb8a/scratchpad/p311.png', fullPage: true })
await browser.close()
