import { chromium } from 'playwright'
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox'] })
const p = await b.newPage({ viewport: { width: 1280, height: 900 } })
await p.goto('http://127.0.0.1:8801/process?code=3.2.3', { waitUntil: 'networkidle' })
await p.waitForTimeout(800)
const missing = await p.$$eval('.proc-missing', (els) => els.map((e) => [e.textContent.trim(), e.getAttribute('title')]))
console.log('elements marked .proc-missing on L3.2.3:', JSON.stringify(missing, null, 1))
const note = await p.$$eval('.proc-missing-note', (els) => els.map((e) => e.textContent.trim()))
console.log('notes:', note)
const links = await p.$$eval('.proc-binding a', (els) => els.map((e) => [e.textContent.trim(), e.getAttribute('href')]))
console.log('links inside the binding:', links)
await p.screenshot({ path: '.scratch/proc-323.png', fullPage: false })
// and the parent, where it appears as a child row
await p.goto('http://127.0.0.1:8801/process?code=3.2', { waitUntil: 'networkidle' })
await p.waitForTimeout(800)
console.log('parent page .proc-missing:', await p.$$eval('.proc-missing', (els) => els.map((e) => e.textContent.trim())))
await p.screenshot({ path: '.scratch/proc-32.png', fullPage: false })
await b.close()
